### PR TITLE
Fix relation from DeVariantSubjectSummary to DeVariantSubjectDetail

### PR DESCRIPTION
**Pull request by mirasrael**
While define relation to *de_variant_subject_detail* table *DeVariantSubjectSummaryCoreDb* ignores *dataset_id* and if you have more than one VCF file loaded with same *chr*, *pos* you will receive all these when referring to details.

### CODE REVIEW

**Comment by cataphract** [comment]
Please start by fixing the build.

**Comment by mirasrael** [comment]
Additional fixes for rsId and fixed test data

**Comment by cataphract** [comment]
If you're fixing a bug, please add a regression test.

**Comment by mirasrael** [comment]
Added test data for regression testing

**Comment by cataphract** [comment]
I don't understand your last commit. You say that the problem is `dataset_id`, but all I see is you adding a new row with a different `rsId`. Can you explain?

**Comment by mirasrael** [comment]
The problem was not only with dataset, but it also related to rsId (I found this later and updated commit). 
If you have multiple records with same (chr,pos), but different rsId (what is allowed by VCF format) it generates wrong result set, because join uses only (chr,pos) pair. This problem may be extended on datasets having records with same (chr,pos). 
So I added samples for records with same (chr,pos) to reproduce this issue. 
I tried to add also other dataset, but didn't find simple way to add it without major copy-paste or refactoring.

**Comment by cataphract** [comment]
OK. I'm still unsatisfied with the test changes though. It is not obvious at all just looking at the test data that the extra record is actually significantly different from the others let one that's it's actually testing a specific bug. In general, I would expect that a regression test be a new test or set of the tests that 1) did not pass before and 2) pass after the changes. Just create a new test method where in its setup phase you write the extra row (you may need to flush the session).

**Comment by mirasrael** [comment]
Added testNonUniquePosChrEntries

**Pull request merged**
