### PR TITLE
adhere to change in criteria look up strategy (alias i.s.o. association

### PR DESCRIPTION
**Pull request by wimvanderlinden**
@cataphract 
September17, 2014, commits labeled "Look up criteria by alias instead of association" (https://github.com/transmart/transmart-core-db/commit/629540bfd73b1f92ba424d4cfc62fc59d4bb0caf) were merged into transmart-core-db. RnaSeqModule.groovy was not updated at that time. This pull request contains this update.

### CODE REVIEW

**Comment by wimvanderlinden** [comment]
@cataphract Please respond to this pull request. Currently, analysis of RNASeq data is not working.

**Comment by cataphract** [comment]
Can you add a test?

**Comment by wimvanderlinden** [comment]
@cataphract I've added the tests you requested.

**Comment by wimvanderlinden** [comment]
@cataphract Could you have a look at this request?

**Pull request closed without merging**
